//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM_Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class datatableEntities1 : DbContext
    {
        public datatableEntities1()
            : base("name=datatableEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<program_parameters> program_parameters { get; set; }
        public virtual DbSet<program> programs { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<users_parameters> users_parameters { get; set; }
        public virtual DbSet<picture> pictures { get; set; }
    }
}
